Use another name for fallback functions to avoid clashing with potential header definitions
* TruffleRuby imports headers from CRuby, notably rb_io_descriptor() but
  existing releases do not implement it yet. So before this change, we get:
  compiling ext/io/console/console.c
  ext/io/console/console.c:92:1: error: static declaration of 'rb_io_descriptor' follows non-static declaration
  rb_io_descriptor(VALUE io)
  truffleruby-dev/lib/cext/include/ruby/io.h:685:5: note: previous declaration is here
  int rb_io_descriptor(VALUE io);